language: node_js
node_js:
  - "9.8.1"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install spamassassin spamc
  - sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/spamassassin
  - sudo service spamassassin start
